# Global settings applied to the whole site.
[build]
  base    = "/"
  publish = "app/"
  command = "yarn run setup"

# Read https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
# to understand how context below works.

# Master branch
[context.production.environment]
  APIHOST = "https://api.opentargets.io/"

# Deploy Preview context: All Deploy Previews (ie.PRs)
# will inherit these settings.
[context.deploy-preview.environment]
  APIHOST = "https://api.opentargets.io/"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy.environment]
  APIHOST = "https://api.opentargets.io/"

# CAREFUL!!! When you point a particular branch to a specific API below,
# the change will not continue working once the branch is merged into master.
[context.feature.environment]
  APIHOST = "https://api.opentargets.io/"

[context."expression-simple".environment]
#  APIHOST = "https://mk-levelupdate-dot-open-targets-eu-dev.appspot.com/api/"
#  APIHOST = "https://mk-zscorefacet-dot-open-targets-eu-dev.appspot.com/api/"
  APIHOST = "https://master-dot-open-targets-eu-dev.appspot.com/"
#  APIHOST = "https://mk-fixfacets-dot-open-targets-eu-dev.appspot.com/api/"

[context.master.environment]
  APIHOST = "https://open-targets-eu-dev.appspot.com/"
